import type { SelectOption } from "@powerhousedao/document-engineering/ui";

// Removed non expense accounts from the list
export const expenseAccountOptions: SelectOption[] = [
  //{ label: "200 - Grants from Maker DAO", value: "200" },
  { label: "2001 - Clearing Account", value: "2001" },
  { label: "2222 - Request Finance IC account", value: "2222" },
  //{ label: "270 - Interest Income", value: "270" },
  { label: "3000 - Activities and Events", value: "3000" },
  { label: "3001 - Meals", value: "3001" },
  { label: "3002 - Airfare", value: "3002" },
  { label: "3003 - Hotels", value: "3003" },
  { label: "3004 - Transportation (Uber, Taxi etc)", value: "3004" },
  { label: "3005 - Other travel cost", value: "3005" },
  //{ label: "310 - Cost of Goods Sold", value: "310" },
  { label: "400 - Advertising", value: "400" },
  { label: "4001 - Legal Fees Abroad", value: "4001" },
  { label: "4002 - Legal Fees Switzerland", value: "4002" },
  { label: "4003 - Finance Team Fees Abroad", value: "4003" },
  { label: "4004 - Finance and Accounting Fees Switzerland", value: "4004" },
  { label: "4005 - Software Development Team Fees", value: "4005" },
  { label: "4006 - Research Team Fees", value: "4006" },
  { label: "4007 - Marketing Team Fees", value: "4007" },
  { label: "4008 - Health Care Fees", value: "4008" },
  { label: "4009 - Contractor Fees", value: "4009" },
  { label: "4010 - Insurance Fees Team", value: "4010" },
  { label: "4011 - HR Fees", value: "4011" },
  { label: "4012 - Team Bonus", value: "4012" },
  { label: "4013 - Refferal Fees", value: "4013" },
  { label: "416 - Depreciation", value: "416" },
  { label: "425 - Freight & Courier", value: "425" },
  { label: "437 - Interest Expense", value: "437" },
  { label: "453 - Office Expenses", value: "453" },
  { label: "469 - Rent", value: "469" },
  { label: "485 - Subscriptions", value: "485" },
  //{ label: "497 - Bank Revaluations", value: "497" },
  //{ label: "498 - Unrealised Currency Gains", value: "498" },
  //{ label: "499 - Realised Currency Gains", value: "499" },
  { label: "505 - Income Tax Expense", value: "505" },
  //{ label: "610 - Accounts Receivable", value: "610" },
  //{ label: "620 - Prepayments", value: "620" },
  //{ label: "630 - Inventory", value: "630" },
  { label: "701 - Software/IT Subscriptions", value: "701" },
  { label: "702 - Telephone and Internet Charges", value: "702" },
  //{ label: "710 - Office Equipment", value: "710" },
  //{ label: "711 - Less Accumulated Depreciation on Office Equipment", value: "711" },
  //{ label: "720 - Computer Equipment", value: "720" },
  //{ label: "721 - Less Accumulated Depreciation on Computer Equipment", value: "721" },
  //{ label: "800 - Accounts Payable", value: "800" },
  { label: "8000 - Bank Fees", value: "8000" },
  { label: "8001 - Gas Fees", value: "8001" },
  { label: "8003 - Exchange Fees", value: "8003" },
  //{ label: "801 - Unpaid Expense Claims", value: "801" },
  //{ label: "802 - Accrued Expenses", value: "802" },
  //{ label: "803 - Wages Payable", value: "803" },
  // { label: "820 - Sales Tax", value: "820" },
  // { label: "825 - Employee Tax Payable", value: "825" },
  // { label: "826 - Superannuation Payable", value: "826" },
  // { label: "830 - Income Tax Payable", value: "830" },
  // { label: "840 - Historical Adjustment", value: "840" },
  // { label: "850 - Suspense", value: "850" },
  // { label: "860 - Rounding", value: "860" },
  // { label: "877 - Tracking Transfers", value: "877" },
  // { label: "880 - Owner A Drawings", value: "880" },
  // { label: "881 - Owner A Funds Introduced", value: "881" },
  // { label: "900 - Loan", value: "900" },
  // { label: "960 - Retained Earnings", value: "960" },
  // { label: "970 - Owner A Share Capital", value: "970" }
];

export const paymentAccountOptions: SelectOption[] = [
  { label: "Clearing Account USD", value: "USD" },
  { label: "Clearing Account EUR", value: "EUR" },
  { label: "Clearing Account DKK", value: "DKK" },
  { label: "Clearing Account GBP", value: "GBP" },
  { label: "Clearing Account JPY", value: "JPY" },
  { label: "Clearing Account CNY", value: "CNY" },
  { label: "Clearing Account CHF", value: "CHF" },
  { label: "Wallet USDS", value: "USDS" },
  { label: "Wallet DAI", value: "DAI" },
  { label: "Wallet EURe", value: "EURe" },
  { label: "Wallet SKY", value: "SKY" },
  { label: "Wallet MKR", value: "MKR" },
  { label: "Wallet USDC", value: "USDC" },
];
